### ISSUE TITLE
pymongo isn't Twisted - asynchronous

### ISSUE THREAD

**Issue by lookfwd** [husless/learning-scrapy#1]
This means that slow DB will block Scrapy's main/only thread.

**Comment by husless** [comment]
PyMongo can work with Gevent's monkey-patching or  Eventlet's.
You can reference this:
https://github.com/mongodb/mongo-python-driver/blob/62e180ac2b4d9c2667b6dba9c3c663223a2574b5/doc/examples/gevent.rst
